## Automation

- alias: Reset settings at midnight
  trigger:
    platform: time
    after: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_notify
        - input_boolean.disable_away_mode


- alias: Away - Lights on
  trigger:
    platform: sun
    event: sunset
    offset: '00:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - condition: state
      entity_id: input_boolean.disable_away_mode
      state: 'off'
    - service: switch.turn_on
      entity_id: switch.living_room_switch_10_0
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Away mode lights on.


- alias: Away mode - Lights off
  trigger:
    platform: sun
    event: sunset
    offset: '06:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - condition: state
      entity_id: input_boolean.disable_away_mode
      state: 'off'
    - service: switch.turn_off
      entity_id: switch.living_room_switch_10_0
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Away mode lights off.


- alias: Send garage status when alarm is armed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_home'
    - platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_away'
  condition:
    condition: state
    entity_id: input_boolean.disable_notify
    state: 'off'
  action:
    - delay: '0:05:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.garage_door_guest_sensor_11_0
          state: 'on'
        - condition: state
          entity_id: binary_sensor.garage_door_jillian_sensor_12_0
          state: 'on'
        - condition: state
          entity_id: binary_sensor.garage_door_jeff_sensor_13_0
          state: 'on'
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Garage door is OPEN.
