## Automation

# Media Center

- alias: Remote - Update UI
  trigger:
    - platform: event
      event_type: homeassistant_start
    - platform: state
      entity_id: remote.family_room
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_room_media
        option: >
          {% if states.remote.family_room.attributes.current_activity == 'Apple TV' %}
            Apple TV
          {% elif states.remote.family_room.attributes.current_activity == 'Cable TV' %}
            Cable TV
          {% elif states.remote.family_room.attributes.current_activity == 'Fire TV' %}
            Fire TV
          {% elif states.remote.family_room.attributes.current_activity == 'DVD Player' %}
            DVD Player
          {% elif states.remote.family_room.attributes.current_activity == 'Music' %}
            Music
          {% else %}
            Power Off
          {% endif %}


- alias: Remote - Change
  trigger:
    platform: state
    entity_id: input_select.family_room_media
  condition:
    condition: template
    value_template: '{{ states.input_select.family_room_media.state != "Power Off" }}'
  action:
    service: remote.turn_on
    data_template:
      entity_id: remote.family_room
      activity: >
        {% if states.input_select.family_room_media.state == 'Apple TV' %}
          21762413
        {% elif states.input_select.family_room_media.state == 'Cable TV' %}
          21762510
        {% elif states.input_select.family_room_media.state == 'Fire TV' %}
          22767959
        {% elif states.input_select.family_room_media.state == 'DVD Player' %}
          21762603
        {% elif states.input_select.family_room_media.state == 'Music' %}
          18890244
        {% endif %}


- alias: Remote - Off
  trigger:
    platform: state
    entity_id: input_select.family_room_media
    to: 'Power Off'
  action:
    service: remote.turn_off
    entity_id: remote.family_room


# Away Mode

- alias: Away - Lights on
  trigger:
    platform: sun
    event: sunset
    offset: '00:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - condition: state
      entity_id: input_boolean.disable_away_mode
      state: 'off'
    - service: switch.turn_on
      entity_id: switch.living_room_switch_10_0
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Away mode lights on.


- alias: Away mode - Lights off
  trigger:
    platform: sun
    event: sunset
    offset: '06:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - condition: state
      entity_id: input_boolean.disable_away_mode
      state: 'off'
    - service: switch.turn_off
      entity_id: switch.living_room_switch_10_0
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Away mode lights off.


- alias: Send garage status when alarm is armed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_home'
    - platform: state
      entity_id: alarm_control_panel.simplisafe
      to: 'armed_away'
  condition:
    condition: state
    entity_id: input_boolean.disable_notify
    state: 'off'
  action:
    - delay: '0:05:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.garage_door_guest_sensor_11_0
          state: 'on'
        - condition: state
          entity_id: binary_sensor.garage_door_jillian_sensor_12_0
          state: 'on'
        - condition: state
          entity_id: binary_sensor.garage_door_jeff_sensor_13_0
          state: 'on'
    - service: notify.sms_jeff
      data:
        title: Home Alert
        message: Garage door is OPEN.


# Misc

- alias: Reset settings at midnight
  trigger:
    platform: time
    after: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_notify
        - input_boolean.disable_away_mode

