homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  packages:
    default: !include packages/default.yaml
    lights: !include packages/lights.yaml
    media: !include packages/media.yaml
    climate: !include packages/climate.yaml
    scenes: !include packages/scenes.yaml
    garage: !include packages/garage.yaml
    settings: !include packages/settings.yaml

frontend:

http:
  api_password: !secret http_password
  trusted_networks: !secret http_trusted_networks

history:

logger:
  default: error

ecobee:
  api_key: !secret ecobee_api_key

alarm_control_panel:
  - platform: simplisafe
    username: !secret simplisafe_user
    password: !secret simplisafe_pass

notify:
  - name: jeffs_phone
    platform: smtp
    server: smtp.gmail.com
    port: 587
    starttls: true
    sender: !secret gmail_sender
    username: !secret gmail_user
    password: !secret gmail_pass
    recipient: !secret jeffs_phone
  - name: jillians_phone
    platform: smtp
    server: smtp.gmail.com
    port: 587
    starttls: true
    sender: !secret gmail_sender
    username: !secret gmail_user
    password: !secret gmail_pass
    recipient: !secret jillians_phone

emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - group
    - scene

zwave: !include zwave.yaml

graphite:

wemo:

sun: