homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  packages:
    default: !include packages/default.yaml
    lights: !include packages/lights.yaml
    media: !include packages/media.yaml
    climate: !include packages/climate.yaml
    scenes: !include packages/scenes.yaml
    inside: !include packages/inside.yaml
    outside: !include packages/outside.yaml
    doors: !include packages/doors.yaml
    settings: !include packages/settings.yaml

frontend:

history:

logger:
  default: warn
  logs:
    homeassistant.components.alarm_control_panel.simplisafe: critical

http: !include config/http.yaml

notify: !include config/notify.yaml

emulated_hue: !include config/emulated_hue.yaml

zwave: !include config/zwave.yaml

sun: