## CONFIGURATION

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend:

http:
  api_password: !secret http_password
  trusted_networks: !secret http_trusted_networks

updater:

history:

logger:
  default: error


# FEATURES

zwave: !include zwave.yaml

ecobee:
  api_key: !secret ecobee_api_key

remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_host

alarm_control_panel:
  - platform: simplisafe
    username: !secret simplisafe_user
    password: !secret simplisafe_pass

notify:
  - name: sms_jeff
    platform: smtp
    server: smtp.gmail.com
    port: 587
    starttls: true
    sender: !secret gmail_sender
    username: !secret gmail_user
    password: !secret gmail_pass
    recipient: !secret sms_jeff_recipient

emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - group
    - scene

graphite:

wemo:

sun:


# COMPONENTS

group: !include group.yaml

sensor: !include sensor.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

scene: !include scene.yaml

automation: !include automation.yaml