homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  packages:
    default: !include packages/default.yaml
    lights: !include packages/lights.yaml
    media: !include packages/media.yaml
    climate: !include packages/climate.yaml
    scenes: !include packages/scenes.yaml
    landscaping: !include packages/landscaping.yaml
    energy: !include packages/energy.yaml
    weather: !include packages/weather.yaml
    settings: !include packages/settings.yaml
    security: !include packages/security.yaml
  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant

auth:

config:

http: !include config/http.yaml

frontend: !include config/frontend.yaml

history: !include config/history.yaml

recorder: !include config/recorder.yaml

influxdb: !include config/influxdb.yaml

notify: !include config/notify.yaml

emulated_hue: !include config/emulated_hue.yaml

zwave: !include config/zwave.yaml

script: !include packages/scripts.yaml

sun:

logger:
  default: warn
  logs:
    homeassistant.components.notify.smtp: error
    homeassistant.components.alarm_control_panel: error
    homeassistant.components.sensor.darksky: error
    homeassistant.helpers.entity: error