## SENSORS

- platform: template
  sensors:
    garage_guest:
      value_template: '{% if is_state("binary_sensor.garage_door_guest_sensor_11_0", "off") %}Closed{% else %}Open{% endif %}'
      entity_id: binary_sensor.garage_door_guest_sensor_11_0
    garage_jeff:
      value_template: '{% if is_state("binary_sensor.garage_door_jillian_sensor_12_0", "off") %}Closed{% else %}Open{% endif %}'
      entity_id: binary_sensor.garage_door_jillian_sensor_12_0
    garage_jillian:
      value_template: '{% if is_state("binary_sensor.garage_door_jeff_sensor_13_0", "off") %}Closed{% else %}Open{% endif %}'
      entity_id: binary_sensor.garage_door_jeff_sensor_13_0
    family_room_status:
      value_template: '{% if is_state("binary_sensor.family_room_occupancy", "on") %}(occupied) {% endif %}{{ states.sensor.family_room_temperature.state }}°F'
      entity_id:
        - binary_sensor.family_room_occupancy
        - sensor.family_room_temperature
    living_room_status:
      value_template: '{% if is_state("binary_sensor.living_room_occupancy", "on") %}(occupied) {% endif %}{{ states.sensor.living_room_temperature.state }}°F'
      entity_id:
        - binary_sensor.living_room_occupancy
        - sensor.living_room_temperature
    masons_room_status:
      value_template: '{% if is_state("binary_sensor.masons_room_occupancy", "on") %}(occupied) {% endif %}{{ states.sensor.masons_room_temperature.state }}°F'
      entity_id:
        - binary_sensor.masons_room_occupancy
        - sensor.masons_room_temperature
    brinks_room_status:
      value_template: '{% if is_state("binary_sensor.brinks_room_occupancy", "on") %}(occupied) {% endif %}{{ states.sensor.brinks_room_temperature.state }}°F'
      entity_id:
        - binary_sensor.brinks_room_occupancy
        - sensor.brinks_room_temperature
    master_bedroom_status:
      value_template: '{% if is_state("binary_sensor.master_bedroom_occupancy", "on") %}(occupied) {% endif %}{{ states.sensor.master_bedroom_temperature.state }}°F'
      entity_id:
        - binary_sensor.master_bedroom_occupancy
        - sensor.master_bedroom_temperature