## SENSORS

- platform: template
  sensors:
    garage_guest:
      value_template: '{% if is_state("binary_sensor.garage_door_guest_sensor_11_0", "off") %}Closed{% else %}Open{% endif %}'
    garage_jeff:
      value_template: '{% if is_state("binary_sensor.garage_door_jillian_sensor_12_0", "off") %}Closed{% else %}Open{% endif %}'
    garage_jillian:
      value_template: '{% if is_state("binary_sensor.garage_door_jeff_sensor_13_0", "off") %}Closed{% else %}Open{% endif %}'
