## SWITCHES


# Media Center

- platform: mqtt
  name: "Apple TV"
  state_topic:   "harmony-api/hubs/family-room/activities/apple-tv/state"
  command_topic: "harmony-api/hubs/family-room/activities/apple-tv/command"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Fire TV"
  state_topic:   "harmony-api/hubs/family-room/activities/fire-tv/state"
  command_topic: "harmony-api/hubs/family-room/activities/fire-tv/command"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Cable TV"
  state_topic:   "harmony-api/hubs/family-room/activities/cable-tv/state"
  command_topic: "harmony-api/hubs/family-room/activities/cable-tv/command"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "DVD Player"
  state_topic:   "harmony-api/hubs/family-room/activities/dvd-player/state"
  command_topic: "harmony-api/hubs/family-room/activities/dvd-player/command"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Music"
  state_topic:   "harmony-api/hubs/family-room/activities/music/state"
  command_topic: "harmony-api/hubs/family-room/activities/music/command"
  payload_on: "on"
  payload_off: "off"