expose_by_default: true
exposed_domains:
  - switch
  - light
  - scene
  - script
entities:
  scene.good_morning:
    hidden: true
  light.kitchen_lights_1_level:
    hidden: true
  light.kitchen_lights_2_level:
    hidden: true
  switch.front_landscape:
    hidden: true
  switch.back_landscape:
    hidden: true
  switch.fountain:
    hidden: true
  script.back_yard_speakers:
    hidden: true
  script.snapshot_door_and_send:
    hidden: true
  script.snapshot_cameras_and_send:
    hidden: true