- name: jeffs_phone
  platform: smtp
  server: smtp.gmail.com
  port: 587
  starttls: true
  sender: !secret gmail_sender
  username: !secret gmail_user
  password: !secret gmail_pass
  recipient: !secret jeffs_phone

- name: jillians_phone
  platform: smtp
  server: smtp.gmail.com
  port: 587
  starttls: true
  sender: !secret gmail_sender
  username: !secret gmail_user
  password: !secret gmail_pass
  recipient: !secret jillians_phone

- name: jeff_and_jillians_phone
  platform: group
  services:
    - service: jeffs_phone
    - service: jillians_phone

- name: alexa_family_room
  platform: command_line
  command: "/config/scripts/alexa_wrapper.sh -d 'Family Room'"

- name: alexa_master_bedroom
  platform: command_line
  command: "/config/scripts/alexa_wrapper.sh -d 'Master Bedroom'"

- name: alexa_all
  platform: command_line
  command: "/config/scripts/alexa_wrapper.sh -d 'ALL'"