## ZWAVE

usb_path: /dev/ttyACM0
polling_interval: 60000
device_config:
  light.pantry_light_level_3_0:
    refresh_value: true
    delay: 5
  light.dining_room_lights_level_2_0:
    refresh_value: true
    delay: 5
  light.master_bedroom_l_level_4_0:
    refresh_value: true
    delay: 5
  light.family_room_lights_level_8_0:
    refresh_value: true
    delay: 5
  light.island_lights_level_5_0:
    refresh_value: true
    delay: 5
  switch.outside_lights_switch_9_0:
    refresh_value: true
    delay: 5
  switch.living_room_switch_10_0:
    refresh_value: true
    delay: 5
  switch.entryway_light_switch_14_0:
    refresh_value: true
    delay: 5
  switch.hallway_light_switch_15_0:
    refresh_value: true
    delay: 5
  switch.kitchen_cabinets_switch_16_0:
    refresh_value: true
    delay: 5