usb_path: /dev/ttyACM0
autoheal: False
polling_interval: 30000
device_config:
  light.dining_room_lights_level:
    refresh_value: True
    delay: 6
    polling_intensity: 2
  light.family_room_lights_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.island_lights_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.kitchen_lights_1_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.kitchen_lights_2_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.masons_room_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.master_bedroom_level:
    refresh_value: True
    delay: 5
    polling_intensity: 1
  light.pantry_light_level:
    refresh_value: True
    delay: 5
    polling_intensity: 2
  switch.entryway_light_switch:
    polling_intensity: 2
  switch.hallway_light_switch:
    polling_intensity: 1
  switch.kitchen_cabinets_switch:
    polling_intensity: 2
  switch.living_room_switch:
    polling_intensity: 1
  switch.back_yard_switch:
    polling_intensity: 1