- alias: Doorbell notifications
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_sensor
    to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_door
        filename: /tmp/snapshot_doorbell.png
    - service: notify.jeff_and_jillians_phone
      data:
        title: Home Assistant
        message: Doorbell
        data:
          images:
            - /tmp/snapshot_doorbell.png


- alias: Turn thermostat to away mode with alarm
  initial_state: True
  trigger:
    platform: state
    entity_id: alarm_control_panel.simplisafe
    to: 'armed_away'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.meadowlands
        away_mode: true


- alias: Turn AC off when house fan turns on
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.house_fan_switch
    from: 'off'
    to: 'on'
  action:
    - condition: template
      value_template: '{{ states.climate.meadowlands.attributes.operation_mode == "cool" }}'
    - service: climate.set_temperature
      data:
        entity_id: climate.meadowlands
        temperature: 80


- alias: Resume thermostat
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.house_fan_switch
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: alarm_control_panel.simplisafe
      from: 'armed_away'
  action:
    - service: climate.ecobee_resume_program
      data:
        entity_id: climate.meadowlands


- alias: Turn the house off when the alarm changes to away
  initial_state: True
  trigger:
    platform: state
    entity_id: alarm_control_panel.simplisafe
    to: 'armed_away'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.all_switches
        - remote.family_room


- alias: Turn lights on when sun sets
  initial_state: True
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_switch
    - service: notify.jeffs_phone
      data:
        title: Home Assistant
        message: Away mode lights on


- alias: Turn lights off if left on
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: '06:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_switch
    - service: notify.jeffs_phone
      data:
        title: Home Assistant
        message: Away mode lights off


- alias: Turn all lights on if alarm goes off
  initial_state: True
  trigger:
    platform: template
    value_template: '{{ states.alarm_control_panel.simplisafe.attributes.alarm != "No Alert" }}'
  action:
    - service: homeassistant.turn_on
      entity_id: group.Lights


- alias: Turn lights off (delayed)
  initial_state: True
  trigger:
    platform: state
    entity_id: input_number.delay_timer
  action:
    - delay: '00:{{ states.input_number.delay_timer.state | int }}:00'
    - condition: numeric_state
      entity_id: input_number.delay_timer
      above: 0
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.all_switches
    - service: input_number.set_value
      data:
        entity_id: input_number.delay_timer
        value: 0


- alias: Update remote UI widget
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: remote.family_room
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_room_media
        option: >
          {% if states.remote.family_room.attributes.current_activity == 'Apple TV' %}
            Apple TV
          {% elif states.remote.family_room.attributes.current_activity == 'Fire TV' %}
            Fire TV
          {% elif states.remote.family_room.attributes.current_activity == 'DVD Player' %}
            DVD Player
          {% elif states.remote.family_room.attributes.current_activity == 'Music' %}
            Music
          {% elif states.remote.family_room.attributes.current_activity == 'Receiver Bluetooth' %}
            Bluetooth
          {% else %}
            Power Off
          {% endif %}


- alias: Turn on device with remote UI widget
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.family_room_media
  action:
    service: remote.turn_on
    data_template:
      entity_id: remote.family_room
      activity: >
        {% if states.input_select.family_room_media.state == 'Apple TV' %}
          21762413
        {% elif states.input_select.family_room_media.state == 'Fire TV' %}
          22767959
        {% elif states.input_select.family_room_media.state == 'DVD Player' %}
          21762603
        {% elif states.input_select.family_room_media.state == 'Music' %}
          18890244
        {% elif states.input_select.family_room_media.state == 'Bluetooth' %}
          22068322
        {% else %}
          -1
        {% endif %}


- alias: Set theme when alarm changes
  initial_state: True
  trigger:
    - platform: state
      entity_id: alarm_control_panel.simplisafe
  action:
    service: frontend.set_theme
    data_template:
      name: >
        {% if states.alarm_control_panel.simplisafe.state == 'armed_home' %}
          alarm
        {% elif states.alarm_control_panel.simplisafe.state == 'armed_away' %}
          alarm
        {% else %}
          default
        {% endif %}
