- id: doorbell_notification
  alias: Doorbell notifications
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_sensor
    to: 'on'
  action:
    - service: notify.jeffs_phone
      data:
        title: Home Assistant
        message: Doorbell
    - service: notify.jillians_phone
      data:
        title: Home Assistant
        message: Doorbell


- id: house_fan_turns_off_ac
  alias: House fan turns off AC
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.house_fan_switch
    to: 'on'
  action:
    - condition: template
      value_template: '{{ states.climate.meadowlands.attributes.operation_mode == "cool" }}'
    - service: climate.set_temperature
      data:
        entity_id: climate.meadowlands
        temperature: 80


- id: house_fan_resumes_ac
  alias: House fan resumes AC
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.house_fan_switch
    to: 'off'
  action:
    - condition: template
      value_template: '{{ states.climate.meadowlands.attributes.operation_mode == "cool" }}'
    - service: climate.ecobee_resume_program
      data:
        entity_id: climate.meadowlands


- id: away_lights_on
  alias: Turn lights on when sun sets
  initial_state: True
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_switch
    - service: notify.jeffs_phone
      data:
        title: Home Assistant
        message: Away mode lights on


- id: away_lights_off
  alias: Turn lights off if left on
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: '06:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.simplisafe
    state: 'armed_away'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_switch
    - service: notify.jeffs_phone
      data:
        title: Home Assistant
        message: Away mode lights off


- id: alarm_lights_on
  alias: Turn all lights on if alarm goes off
  initial_state: True
  trigger:
    platform: state
    entity_id: alarm_control_panel.simplisafe
    to: 'triggered'
  action:
    - service: homeassistant.turn_on
      entity_id: group.Lights


- id: remote_update
  alias: Update remote UI widget
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: remote.family_room
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_room_media
        option: >
          {% if states.remote.family_room.attributes.current_activity == 'Apple TV' %}
            Apple TV
          {% elif states.remote.family_room.attributes.current_activity == 'Fire TV' %}
            Fire TV
          {% elif states.remote.family_room.attributes.current_activity == 'DVD Player' %}
            DVD Player
          {% elif states.remote.family_room.attributes.current_activity == 'Music' %}
            Music
          {% elif states.remote.family_room.attributes.current_activity == 'Receiver Bluetooth' %}
            Bluetooth
          {% else %}
            Power Off
          {% endif %}


- id: remote_change
  alias: Turn on device with remote UI widget
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.family_room_media
  action:
    service: remote.turn_on
    data_template:
      entity_id: remote.family_room
      activity: >
        {% if states.input_select.family_room_media.state == 'Apple TV' %}
          21762413
        {% elif states.input_select.family_room_media.state == 'Fire TV' %}
          22767959
        {% elif states.input_select.family_room_media.state == 'DVD Player' %}
          21762603
        {% elif states.input_select.family_room_media.state == 'Music' %}
          18890244
        {% elif states.input_select.family_room_media.state == 'Bluetooth' %}
          22068322
        {% else %}
          -1
        {% endif %}


- id: settings_lights_off
  alias: Turn lights off (delayed)
  initial_state: True
  trigger:
    platform: numeric_state
    entity_id: input_slider.delay_timer
    above: 0
  action:
    - delay: '00:{{ states.input_slider.delay_timer.state | int }}:00'
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.all_switches
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.delay_timer
        value: 0


- id: change_theme_after_sunrise
  alias: Change theme after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: default


- id: change_theme_after_sunset
  alias: Change theme after sunset
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: dark