group:
  Climate:
    entities:
      - sensor.climate_temp
      - sensor.climate_humidity
      - sensor.climate_mode
      - switch.house_fan_switch


homeassistant:
  customize:
    sensor.climate_temp:
      friendly_name: Temperature
    sensor.climate_humidity:
      friendly_name: Humidity
      icon: mdi:water
    sensor.climate_mode:
      friendly_name: Mode
      icon: mdi:nest-thermostat
    sensor.meadowlands_temperature:
      hidden: true
    sensor.meadowlands_humidity:
      hidden: true
    switch.house_fan_switch:
      friendly_name: House Fan
      icon: mdi:fan


ecobee:
  api_key: !secret ecobee_api_key


sensor:
  - platform: template
    sensors:
      climate_temp:
        value_template: '{{states.climate.meadowlands.attributes.current_temperature}}'
        unit_of_measurement: °F
        entity_id:
          - climate.meadowlands

      climate_humidity:
        value_template: '{{states.climate.meadowlands.attributes.actual_humidity}}'
        unit_of_measurement: '%'
        entity_id:
          - climate.meadowlands

      climate_mode:
        value_template: '{{states.climate.meadowlands.attributes.operation_mode|capitalize}}{% if states.climate.meadowlands.attributes.away_mode == "on" %} (Away){% endif %}'
        entity_id:
          - climate.meadowlands


