

sensor:
  - platform: template
    sensors:
      family_room_status:
        value_template: '{% if is_state("binary_sensor.family_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.family_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.family_room_occupancy
          - sensor.family_room_temperature
      living_room_status:
        value_template: '{% if is_state("binary_sensor.living_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.living_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.living_room_occupancy
          - sensor.living_room_temperature
      masons_room_status:
        value_template: '{% if is_state("binary_sensor.masons_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.masons_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.masons_room_occupancy
          - sensor.masons_room_temperature
      brinks_room_status:
        value_template: '{% if is_state("binary_sensor.brinks_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.brinks_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.brinks_room_occupancy
          - sensor.brinks_room_temperature
      master_bedroom_status:
        value_template: '{% if is_state("binary_sensor.master_bedroom_occupancy", "on") %}☺ {% endif %}{{ states.sensor.master_bedroom_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.master_bedroom_occupancy
          - sensor.master_bedroom_temperature
      climate_temp:
        value_template: '{{states.climate.meadowlands.attributes.current_temperature}}'
        unit_of_measurement: °F
        entity_id:
          - climate.meadowlands
      climate_humidity:
        value_template: '{{states.climate.meadowlands.attributes.actual_humidity}}'
        unit_of_measurement: '%'
        entity_id:
          - climate.meadowlands
      climate_mode:
        value_template: '{{states.climate.meadowlands.attributes.operation_mode|capitalize}}{% if states.climate.meadowlands.attributes.away_mode == "on" %} (Away){% endif %}'
        entity_id:
          - climate.meadowlands

  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - dew_point
      - wind_speed
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - temperature_max
      - temperature_min




group:
  climate:
    name: Climate
    entities:
      - sensor.climate_temp
      - sensor.climate_humidity
      - sensor.climate_mode
      - switch.house_fan

  rooms:
    name: Rooms
    entities:
      - sensor.family_room_status
      - sensor.living_room_status
      - sensor.masons_room_status
      - sensor.brinks_room_status
      - sensor.master_bedroom_status


  outside:
    name: Outside
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_humidity
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_pressure
      - sensor.dark_sky_visibility
      - sensor.dark_sky_cloud_coverage
