group:
  climate:
    name: Climate
    entities:
      - sensor.climate_mode
      - switch.house_fan_switch
      - sensor.family_room_status
      - sensor.living_room_status
      - sensor.masons_room_status
      - sensor.master_bedroom_status


homeassistant:
  customize:
    sensor.climate_temp:
      friendly_name: Temperature
    sensor.climate_humidity:
      friendly_name: Humidity
      icon: mdi:water
    sensor.climate_mode:
      friendly_name: Mode
      icon: mdi:thermostat
    sensor.home_temperature:
      hidden: true
    sensor.home_humidity:
      hidden: true
    switch.house_fan_switch:
      friendly_name: House Fan
      icon: mdi:fan
    sensor.family_room_temperature:
      hidden: true
    sensor.living_room_temperature:
      hidden: true
    sensor.masons_room_temperature:
      hidden: true


ecobee:
  api_key: !secret ecobee_api_key


sensor:
  - platform: template
    sensors:
      climate_mode:
        value_template: "{% if states.climate.home.attributes.mode == 'Away' %}Away{% else %}{{ states.climate.home.attributes.operation_mode|capitalize }}{% endif %}"

      climate_operation:
        value_template: "{{ states.climate.home.attributes.operation }}"

      family_room_status:
        friendly_name: Family Room
        value_template: "{{ states.sensor.family_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.family_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      living_room_status:
        friendly_name: Living Room
        value_template: "{{ states.sensor.living_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.living_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      masons_room_status:
        friendly_name: Mason's Bedroom
        value_template: "{{ states.sensor.masons_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.masons_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      master_bedroom_status:
        friendly_name: Master Bedroom
        value_template: "{{ states.sensor.master_bedroom_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}


automation:
  - alias: Climate - House fan disables HVAC
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.house_fan_switch
      from: "off"
      to: "on"
    action:
      - condition: template
        value_template: "{{ states.climate.home.attributes.operation_mode == 'cool' }}"
      - service: climate.set_temperature
        data:
          entity_id: climate.home
          temperature: 80

  - alias: Climate – Resume thermostat
    initial_state: True
    hide_entity: True
    trigger:
      - platform: state
        entity_id: switch.house_fan_switch
        from: "on"
        to: "off"
    action:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.home
