group:
  default_view:
    name: Inside
    view: yes
    entities:
      - group.lights
      - group.media
      - group.climate
      - group.scenes
  outside:
    view: yes
    entities:
      - group.weather
      - group.landscaping
      - group.security
  tools:
    view: yes
    entities:
      - group.settings
      - group.energy
      - group.network
      - group.all_automations
