group:
  default_view:
      view: yes
      entities:
        - updater.updater
        - alert.garage_door_guest
        - alert.garage_door_jeff
        - alert.garage_door_jillian
        - group.Lights
        - group.Media
        - group.Climate
        - group.Scenes
  status:
    view: yes
    entities:
      - group.Inside
      - group.Outside
      - group.Garage
  admin:
    view: yes
    entities:
      - group.Settings
