group:
  default_view:
    view: yes
    entities:
      - group.Lights
      - group.Media
      - group.Climate
      - group.Scenes
  status:
    view: yes
    entities:
      - group.Inside
      - group.Outside
      - group.Sensors
  tools:
    view: yes
    entities:
      - alert.garage_door_guest
      - alert.garage_door_jeff
      - alert.garage_door_jillian
      - group.Settings
      - group.all_automations


homeassistant:
  customize:
    group.all_automations:
      friendly_name: Automations
      control: hidden
      hidden: false
