group:
  default_view:
      view: yes
      entities:
        - updater.updater
        - alert.garage_door_guest
        - alert.garage_door_jeff
        - alert.garage_door_jillian
        - group.Lights
        - group.Media
        - group.Climate
        - group.Scenes
  status:
    view: yes
    entities:
      - group.Inside
      - group.Outside
      - group.Garage
  admin:
    view: yes
    entities:
      - group.Settings


homeassistant:
  customize:
    group.all_automations:
      emulated_hue: false
    group.all_remotes:
      emulated_hue: false
    group.climate:
      emulated_hue: false
    group.default_view:
      emulated_hue: false
    group.garage:
      emulated_hue: false
    group.lights:
      emulated_hue: false
    group.media_center:
      emulated_hue: false
    group.rooms:
      emulated_hue: false
    group.scenes:
      emulated_hue: false
    group.settings:
      emulated_hue: false
    group.status:
      emulated_hue: false
    group.toggles:
      emulated_hue: false
