group:
  default_view:
    view: yes
    entities:
      - group.Lights
      - group.Media
      - group.Climate
      - group.Scenes
  status:
    view: yes
    entities:
      - group.Inside
      - group.Outside
      - group.Sensors
  admin:
    view: yes
    entities:
      - alert.garage_door_guest
      - alert.garage_door_jeff
      - alert.garage_door_jillian
      - input_slider.delay_timer
