group:
  default_view:
    name: Inside
    view: yes
    entities:
      - group.Lights
      - group.Media
      - group.Climate
      - group.Scenes
  outside:
    view: yes
    entities:
      - group.Weather
      - group.Landscaping
      - group.Sensors
  tools:
    view: yes
    entities:
      - alert.garage_door_guest
      - alert.garage_door_jeff
      - alert.garage_door_jillian
      - group.Settings
      - group.Energy
      - group.Batteries
      - group.all_automations
