group:
  Garage:
    entities:
      - sensor.garage_jillian
      - sensor.garage_jeff
      - sensor.garage_guest


homeassistant:
  customize:
    sensor.garage_guest:
      friendly_name: Guest Door
      icon: mdi:home
    sensor.garage_jeff:
      friendly_name: Jeff's Door
      icon: mdi:home
    sensor.garage_jillian:
      friendly_name: Jillian's Door
      icon: mdi:home


alarm_control_panel:
  - platform: simplisafe
    username: !secret simplisafe_user
    password: !secret simplisafe_pass


sensor:
  - platform: template
    sensors:
      garage_guest:
        value_template: '{% if is_state("binary_sensor.guest_garage_door_sensor", "on") %}Open{% elif is_state("binary_sensor.guest_garage_door_sensor", "off") %}Closed{% else %}Unknown{% endif %}'
        entity_id: binary_sensor.guest_garage_door_sensor

      garage_jillian:
        value_template: '{% if is_state("binary_sensor.jillians_garage_door_sensor", "on") %}Open{% elif is_state("binary_sensor.jillians_garage_door_sensor", "off") %}Closed{% else %}Unknown{% endif %}'
        entity_id: binary_sensor.jillians_garage_door_sensor

      garage_jeff:
        value_template: '{% if is_state("binary_sensor.jeffs_garage_door_sensor", "on") %}Open{% elif is_state("binary_sensor.jeffs_garage_door_sensor", "off") %}Closed{% else %}Unknown{% endif %}'
        entity_id: binary_sensor.jeffs_garage_door_sensor


alert:
  garage_door_jeff:
    name: Jeff's garage is open
    entity_id: binary_sensor.jeffs_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone

  garage_door_jillian:
    name: Jillian's garage is open
    entity_id: binary_sensor.jillians_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone

  garage_door_guest:
    name: Guest garage is open
    entity_id: binary_sensor.guest_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone