group:
  Garage:
    entities:
      - sensor.garage_jillian
      - sensor.garage_jeff
      - sensor.garage_guest


homeassistant:
  customize:
    sensor.garage_guest:
      friendly_name: Guest Door
      icon: mdi:home
    sensor.garage_jeff:
      friendly_name: Jeff's Door
      icon: mdi:home
    sensor.garage_jillian:
      friendly_name: Jillian's Door
      icon: mdi:home
    binary_sensor.garage_door_guest_sensor:
      hidden: true
    binary_sensor.garage_door_jillian_sensor:
      hidden: true
    binary_sensor.garage_door_jeff_sensor:
      hidden: true
    sensor.garage_door_guest_alarm_type:
      hidden: true
    sensor.garage_door_guest_alarm_level:
      hidden: true
    sensor.garage_door_guest_sourcenodeid:
      hidden: true
    sensor.garage_door_guest_burglar:
      hidden: true
    sensor.garage_door_jillian_alarm_type:
      hidden: true
    sensor.garage_door_jillian_alarm_level:
      hidden: true
    sensor.garage_door_jillian_sourcenodeid:
      hidden: true
    sensor.garage_door_jillian_burglar:
      hidden: true
    sensor.garage_door_jeff_alarm_type:
      hidden: true
    sensor.garage_door_jeff_alarm_level:
      hidden: true
    sensor.garage_door_jeff_sourcenodeid:
      hidden: true
    sensor.garage_door_jeff_burglar:
      hidden: true


sensor:
  - platform: template
    sensors:
      garage_guest:
        value_template: '{% if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor", "off") %}Closed{% else %}Open{% endif %}'
        entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor

      garage_jillian:
        value_template: '{% if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_2", "off") %}Closed{% else %}Open{% endif %}'
        entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_2

      garage_jeff:
        value_template: '{% if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_3", "off") %}Closed{% else %}Open{% endif %}'
        entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_3


alert:
  garage_door_jeff:
    name: Jeff's garage is open
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_3
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone

  garage_door_jillian:
    name: Jillian's garage is open
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_2
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone

  garage_door_guest:
    name: Guest garage is open
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
    state: 'on'
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeffs_phone
      - jillians_phone