group:
  Inside:
    entities:
      - sensor.family_room_status
      - sensor.living_room_status
      - sensor.masons_room_status
      - sensor.brinks_room_status
      - sensor.master_bedroom_status


homeassistant:
  customize:
    sensor.family_room_temperature:
      hidden: true
    sensor.living_room_temperature:
      hidden: true
    sensor.masons_room_temperature:
      hidden: true
    sensor.brinks_room_temperature:
      hidden: true
    sensor.family_room_status:
      friendly_name: Family Room
      icon: mdi:thermometer
    sensor.living_room_status:
      friendly_name: Living Room
      icon: mdi:thermometer
    sensor.masons_room_status:
      friendly_name: Mason's Bedroom
      icon: mdi:thermometer
    sensor.brinks_room_status:
      friendly_name: Brinkley's Bedroom
      icon: mdi:thermometer
    sensor.master_bedroom_status:
      friendly_name: Master Bedroom
      icon: mdi:thermometer


sensor:
  - platform: template
    sensors:
      family_room_status:
        value_template: '{% if is_state("binary_sensor.family_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.family_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.family_room_occupancy
          - sensor.family_room_temperature

      living_room_status:
        value_template: '{% if is_state("binary_sensor.living_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.living_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.living_room_occupancy
          - sensor.living_room_temperature

      masons_room_status:
        value_template: '{% if is_state("binary_sensor.masons_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.masons_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.masons_room_occupancy
          - sensor.masons_room_temperature

      brinks_room_status:
        value_template: '{% if is_state("binary_sensor.brinks_room_occupancy", "on") %}☺ {% endif %}{{ states.sensor.brinks_room_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.brinks_room_occupancy
          - sensor.brinks_room_temperature

      master_bedroom_status:
        value_template: '{% if is_state("binary_sensor.master_bedroom_occupancy", "on") %}☺ {% endif %}{{ states.sensor.master_bedroom_temperature.state }}'
        unit_of_measurement: °F
        entity_id:
          - binary_sensor.master_bedroom_occupancy
          - sensor.master_bedroom_temperature