group:
  Inside:
    entities:
      - sensor.family_room_status
      - sensor.living_room_status
      - sensor.masons_room_status
      - sensor.brinks_room_status
      - sensor.master_bedroom_status


homeassistant:
  customize:
    sensor.family_room_temperature:
      hidden: true
    sensor.living_room_temperature:
      hidden: true
    sensor.masons_room_temperature:
      hidden: true
    sensor.brinks_room_temperature:
      hidden: true


sensor:
  - platform: template
    sensors:
      family_room_status:
        friendly_name: Family Room
        value_template: '{{ states.sensor.family_room_temperature.state|round|int }}'
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state('binary_sensor.family_room_occupancy', 'on') -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      living_room_status:
        friendly_name: Living Room
        value_template: '{{ states.sensor.living_room_temperature.state|round|int }}'
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state('binary_sensor.living_room_occupancy', 'on') -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      masons_room_status:
        friendly_name: Mason's Bedroom
        value_template: '{{ states.sensor.masons_room_temperature.state|round|int }}'
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state('binary_sensor.masons_room_occupancy', 'on') -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      brinks_room_status:
        friendly_name: Brinkley's Bedroom
        value_template: '{{ states.sensor.brinks_room_temperature.state|round|int }}'
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state('binary_sensor.brinks_room_occupancy', 'on') -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      master_bedroom_status:
        friendly_name: Master Bedroom
        value_template: '{{ states.sensor.master_bedroom_temperature.state|round|int }}'
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state('binary_sensor.master_bedroom_occupancy', 'on') -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}