group:
  landscaping:
    name: Landscaping
    control: hidden
    entities:
      - switch.front_yard_switch
      - switch.back_yard_switch
      - switch.front_landscape
      - switch.back_landscape
      - switch.fountain


homeassistant:
  customize:
    switch.front_yard_switch:
      friendly_name: Front Light
      icon: mdi:lightbulb
    switch.back_yard_switch:
      friendly_name: Back Light
      icon: mdi:lightbulb
    switch.front_landscape:
      friendly_name: Front Landscape
      icon: mdi:lightbulb
    switch.back_landscape:
      friendly_name: Back Landscape
      icon: mdi:lightbulb
    switch.fountain:
      friendly_name: Fountain
      icon: mdi:cup-water


automation:
  - alias: Landscape - Lights
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:15:00"
      # off
      - platform: time
        at: "22:00:00"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id:
          - switch.front_landscape
          - switch.back_landscape


  - alias: Landscape - Front door light
    initial_state: True
    trigger:
      # on
      - platform: time
        at: "22:00:00"
      # off
      - platform: sun
        event: sunrise
        offset: "-01:00:00"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunrise" %}off{% else %}on{% endif %}
        entity_id:
          switch.front_yard_switch

  - alias: Landscape - Fountain
    initial_state: True
    trigger:
      # on
      - platform: time
        at: "09:00:00"
      # off
      - platform: sun
        event: sunset
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}off{% else %}on{% endif %}
        entity_id:
          switch.fountain

  - alias: Landscape - Back door light
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.family_room_doors
        to: "on"
      - platform: state
        entity_id: binary_sensor.master_bedroom_doors
        to: "on"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.back_yard_switch