group:
  Lights:
    entities:
      - group.Kitchen
      - light.island_lights_level
      - switch.kitchen_cabinets_switch
      - light.family_room_lights_level
      - light.pantry_light_level
      - light.dining_room_lights_level
      - switch.living_room_switch
      - switch.entryway_light_switch
      - switch.hallway_light_switch
      - light.master_bedroom_l_level
      - light.masons_room_level
      - switch.outside_lights_switch
  Kitchen:
    entities:
      - light.kitchen_lights_1_level
      - light.kitchen_lights_2_level


homeassistant:
  customize:
    light.pantry_light_level:
      friendly_name: Pantry
    light.dining_room_lights_level:
      friendly_name: Dining Room
    light.master_bedroom_l_level:
      friendly_name: Master Bedroom
    light.family_room_lights_level:
      friendly_name: Family Room
    light.island_lights_level:
      friendly_name: Island
    light.masons_room_level:
      friendly_name: Mason's Bedroom
    light.kitchen_lights_1_level:
      hidden: true
      emulated_hue_hidden: true
    light.kitchen_lights_2_level:
      hidden: true
      emulated_hue_hidden: true
    switch.outside_lights_switch:
      friendly_name: Back Yard
      icon: mdi:lightbulb
    switch.living_room_switch:
      friendly_name: Living Room
      icon: mdi:lightbulb
    switch.entryway_light_switch:
      friendly_name: Entryway
      icon: mdi:lightbulb
    switch.hallway_light_switch:
      friendly_name: Hallway
      icon: mdi:lightbulb
    switch.kitchen_cabinets_switch:
      friendly_name: Kitchen Cabinets
      icon: mdi:lightbulb
    group.Kitchen:
      emulated_hue_hidden: false


automation:
  - alias: Sun setting in away mode turns lights on
    initial_state: True
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_away'
    action:
      - service: switch.turn_on
        entity_id: switch.living_room_switch
      - service: notify.jeffs_phone
        data:
          title: Home Assistant
          message: Away mode lights on

  - alias: Sun rising in away mode turns lights off
    initial_state: True
    trigger:
      platform: sun
      event: sunset
      offset: '06:00:00'
    condition:
      condition: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_away'
    action:
      - service: switch.turn_off
        entity_id: switch.living_room_switch
      - service: notify.jeffs_phone
        data:
          title: Home Assistant
          message: Away mode lights off

  - alias: Delay lights off when timer changes
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.delay_timer
    action:
      - delay: '00:{{ states.input_number.delay_timer.state | int }}:00'
      - condition: numeric_state
        entity_id: input_number.delay_timer
        above: 0
      - service: homeassistant.turn_off
        entity_id:
          - group.all_lights
          - group.all_switches
      - service: input_number.set_value
        data:
          entity_id: input_number.delay_timer
          value: 0