group:
  Lights:
    entities:
      - light.family_room_lights_level
      - light.dining_room_lights_level
      - switch.living_room_switch
      - light.Kitchen
      - light.island_lights_level
      - switch.kitchen_cabinets_switch
      - light.pantry_light_level
      - switch.entryway_light_switch
      - switch.hallway_light_switch
      - switch.guest_room_switch
      - light.masons_room_level
      - light.master_bedroom_level

light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_lights_1_level
      - light.kitchen_lights_2_level


homeassistant:
  customize:
    light.pantry_light_level:
      friendly_name: Pantry
    light.dining_room_lights_level:
      friendly_name: Dining Room
    light.master_bedroom_level:
      friendly_name: Master Bedroom
    light.family_room_lights_level:
      friendly_name: Family Room
    light.island_lights_level:
      friendly_name: Island
    light.masons_room_level:
      friendly_name: Mason's Bedroom
    light.kitchen_lights_1_level:
      hidden: true
      emulated_hue_hidden: true
    light.kitchen_lights_2_level:
      hidden: true
      emulated_hue_hidden: true
    switch.guest_room_switch:
      friendly_name: Guest Bedroom
      icon: mdi:lightbulb
    switch.living_room_switch:
      friendly_name: Living Room
      icon: mdi:lightbulb
    switch.entryway_light_switch:
      friendly_name: Entryway
      icon: mdi:lightbulb
    switch.hallway_light_switch:
      friendly_name: Hallway
      icon: mdi:lightbulb
    switch.kitchen_cabinets_switch:
      friendly_name: Kitchen Cabinets
      icon: mdi:lightbulb
    light.Kitchen:
      friendly_name: Kitchen
      icon: mdi:lightbulb


automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "23:03:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.abode
      state: "armed_away"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room_switch
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Home Assistant
          message: I am turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode
      from: "armed_away"
      to: "disarmed"
    action:
      - condition: sun
        after: sunset
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_light_switch