light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_lights_1_level
      - light.kitchen_lights_2_level

automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "23:03:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.abode
      state: "armed_away"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room_switch
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Home Assistant
          message: I am turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: sun
      after: sunset
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_light_switch
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.master_bedroom
          message: Welcome home. I turned the lights on for you.