## Lights


group:
  lights:
    entities:
      - group.kitchen_lights
      - light.island_lights_level_5_0
      - switch.kitchen_cabinets_switch_16_0
      - light.family_room_lights_level_8_0
      - light.pantry_light_level_3_0
      - light.dining_room_lights_level_2_0
      - switch.living_room_switch_10_0
      - switch.entryway_light_switch_14_0
      - switch.hallway_light_switch_15_0
      - light.master_bedroom_l_level_4_0
      - switch.outside_lights_switch_9_0

  kitchen_lights:
    name: Kitchen
    entities:
      - light.kitchen_lights_1_level_7_0
      - light.kitchen_lights_2_level_6_0


automation:
  - alias: Away - Lights on with sun
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_away'
    action:
      - condition: state
        entity_id: input_boolean.disable_away_mode
        state: 'off'
      - service: switch.turn_on
        entity_id: switch.living_room_switch_10_0
      - service: notify.jeffs_phone
        data:
          title: Home Assistant
          message: Away mode lights on

  - alias: Away mode - Lights off with sun
    trigger:
      platform: sun
      event: sunset
      offset: '06:00:00'
    condition:
      condition: state
      entity_id: alarm_control_panel.simplisafe
      state: 'armed_away'
    action:
      - condition: state
        entity_id: input_boolean.disable_away_mode
        state: 'off'
      - service: switch.turn_off
        entity_id: switch.living_room_switch_10_0
      - service: notify.jeffs_phone
        data:
          title: Home Assistant
          message: Away mode lights off