
input_select:
  family_room_media:
    name: Family Room
    options:
      - Power Off
      - Apple TV
      - Fire TV
      - DVD Player
      - Music
      - Bluetooth
    initial: Power Off
    icon: mdi:television


group:
  media_center:
    name: Media
    entities:
      - input_select.family_room_media


automation:
  - alias: Remote - Update UI
    trigger:
      - platform: event
        event_type: homeassistant_start
      - platform: state
        entity_id: remote.family_room
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.family_room_media
          option: >
            {% if states.remote.family_room.attributes.current_activity == 'Apple TV' %}
              Apple TV
            {% elif states.remote.family_room.attributes.current_activity == 'Fire TV' %}
              Fire TV
            {% elif states.remote.family_room.attributes.current_activity == 'DVD Player' %}
              DVD Player
            {% elif states.remote.family_room.attributes.current_activity == 'Music' %}
              Music
            {% elif states.remote.family_room.attributes.current_activity == 'Receiver Bluetooth' %}
              Bluetooth
            {% else %}
              Power Off
            {% endif %}


  - alias: Remote - Change
    trigger:
      platform: state
      entity_id: input_select.family_room_media
    action:
      service: remote.turn_on
      data_template:
        entity_id: remote.family_room
        activity: >
          {% if states.input_select.family_room_media.state == 'Apple TV' %}
            21762413
          {% elif states.input_select.family_room_media.state == 'Fire TV' %}
            22767959
          {% elif states.input_select.family_room_media.state == 'DVD Player' %}
            21762603
          {% elif states.input_select.family_room_media.state == 'Music' %}
            18890244
          {% elif states.input_select.family_room_media.state == 'Bluetooth' %}
            22068322
          {% else %}
            -1
          {% endif %}