group:
  Outside:
    control: hidden
    entities:
      - switch.front_yard_switch
#      - switch.skybell_front_door_do_not_disturb
      - sensor.outdoor_temperature
      - sensor.outdoor_wind_speed
      - sensor.outdoor_humidity


homeassistant:
  customize:
    switch.skybell_front_door_do_not_disturb:
      friendly_name: Mute Doorbell
      icon: mdi:bell


# skybell:
#   username: !secret skybell_user
#   password: !secret skybell_pass


# switch:
#   - platform: skybell
#     monitored_conditions:
#       - do_not_disturb

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - wind_speed
      - humidity

  - platform: template
    sensors:
      outdoor_temperature:
        friendly_name: Temperature
        value_template: '{{ states.sensor.dark_sky_temperature.state|round|int }}'
        unit_of_measurement: °F
        icon_template: mdi:thermometer

      outdoor_wind_speed:
        friendly_name: Wind Speed
        value_template: '{{ states.sensor.dark_sky_wind_speed.state|round|int }}'
        unit_of_measurement: 'mph'
        icon_template: mdi:weather-windy

      outdoor_humidity:
        friendly_name: Humidity
        value_template: '{{ states.sensor.dark_sky_humidity.state|round|int }}'
        unit_of_measurement: '%'
        icon_template: mdi:water