group:
  Outside:
    entities:
      - sensor.front_lights
      - sensor.outdoor_temperature
      - sensor.outdoor_wind_speed
      - sensor.outdoor_humidity


sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - wind_speed
      - humidity

  - platform: template
    sensors:
      front_lights:
        friendly_name: Front Lights
        value_template: '{{ states.switch.front_yard_switch.state }}'
        entity_picture_template: >
          {%- if is_state('switch.front_yard_switch', 'on') -%}
            /local/lightbulb-on.svg
          {%- else -%}
            /local/lightbulb.svg
          {%- endif -%}

      outdoor_temperature:
        friendly_name: Temperature
        value_template: '{{ states.sensor.dark_sky_temperature.state|round|int }}'
        unit_of_measurement: °F
        icon_template: mdi:thermometer

      outdoor_wind_speed:
        friendly_name: Wind Speed
        value_template: '{{ states.sensor.dark_sky_wind_speed.state|round|int }}'
        unit_of_measurement: 'mph'
        icon_template: mdi:weather-windy

      outdoor_humidity:
        friendly_name: Humidity
        value_template: '{{ states.sensor.dark_sky_humidity.state|round|int }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent