group:
  Yard:
    name: Outside
    control: hidden
    entities:
      - sensor.dark_sky_summary      
      - sensor.outdoor_temperature
      - switch.front_yard_switch
      - switch.back_yard_switch
      - switch.front_landscape
      - switch.back_landscape
      - switch.fountain
      - switch.skybell_front_door_do_not_disturb


homeassistant:
  customize:
    switch.front_yard_switch:
      friendly_name: Front Light
      icon: mdi:lightbulb
    switch.back_yard_switch:
      friendly_name: Back Light
      icon: mdi:lightbulb
    switch.front_landscape:
      friendly_name: Front Landscape
      icon: mdi:lightbulb
    switch.back_landscape:
      friendly_name: Back Landscape
      icon: mdi:lightbulb
    switch.fountain:
      friendly_name: Fountain
      icon: mdi:fountain
    switch.skybell_front_door_do_not_disturb:
      friendly_name: Mute Doorbell
      icon: mdi:bell
    sensor.dark_sky_summary:
      friendly_name: Today
      icon: mdi:weather-sunny
      entity_picture:


skybell:
  username: !secret skybell_user
  password: !secret skybell_pass

switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - summary
      - humidity

  - platform: template
    sensors:
      outdoor_temperature:
        friendly_name: Temperature
        value_template: '{{ states.sensor.dark_sky_temperature.state|round|int }}'
        unit_of_measurement: °F
        icon_template: mdi:thermometer


automation:
  - alias: Landscape lights on
    initial_state: True
    trigger:
      platform: sun
      event: sunset
    action:
      - service: switch.turn_on
        entity_id:
          - switch.front_landscape
          - switch.back_landscape

  - alias: Landscape lights off
    initial_state: True
    trigger:
      platform: time
      at: '22:00:00'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.front_landscape
          - switch.back_landscape

  - alias: Front door light on
    initial_state: True
    trigger:
      platform: time
      at: '22:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.front_yard_switch

  - alias: Front lights off with sunrise
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
      offset: '-01:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.front_yard_switch