group:
  Outside:
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_humidity


homeassistant:
  customize:
    sensor.dark_sky_temperature:
      friendly_name: Temperature
    sensor.dark_sky_wind_speed:
      friendly_name: Wind Speed
    sensor.dark_sky_humidity:
      friendly_name: Humidity

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - wind_speed
      - humidity