group:
  Outside:
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_humidity
      - sensor.front_lights


homeassistant:
  customize:
    sensor.dark_sky_temperature:
      friendly_name: Temperature
    sensor.dark_sky_wind_speed:
      friendly_name: Wind Speed
    sensor.dark_sky_humidity:
      friendly_name: Humidity
    sensor.front_lights:
      friendly_name: Front Lights

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - wind_speed
      - humidity

  - platform: template
    sensors:
      front_lights:
        value_template: '{{ states.switch.front_yard_switch.state }}'
        entity_picture_template: >
          {%- if is_state('switch.front_yard_switch', 'on') -%}
            /local/lightbulb-on.svg
          {%- else -%}
            /local/lightbulb.svg
          {%- endif -%}