group:
  Scenes:
    entities:
      - scene.good_morning
      - scene.good_night
      - scene.cook_time
      - scene.night_time


homeassistant:
  customize:
    scene.night_time:
      icon: mdi:movie
    scene.cook_time:
      icon: mdi:food-variant
    scene.good_morning:
      icon: mdi:brightness-5
    scene.good_night:
      icon: mdi:brightness-2


scene:
  - name: Night Time
    entities:
      light.kitchen_lights_1_level:
        state: on
        brightness: 40
      light.kitchen_lights_2_level:
        state: on
        brightness: 40
      light.island_lights_level: off
      light.family_room_lights_level: off
      light.pantry_light_level: off

  - name: Cook Time
    entities:
      light.kitchen_lights_1_level:
        state: on
        brightness: 120
      light.kitchen_lights_2_level:
        state: on
        brightness: 120
      light.family_room_lights_level:
        state: on
        brightness: 40
      light.island_lights_level: off
      light.pantry_light_level: off

  - name: Good Morning
    entities:
      alarm_control_panel.simplisafe: 'disarmed'
      switch.kitchen_cabinets_switch:
        state: on
      light.island_lights_level:
        state: on
        brightness: 127

  - name: Good Night
    entities:
      group.all_lights: off
      group.all_switches: off
      alarm_control_panel.simplisafe: 'armed_home'
