group:
  Scenes:
    entities:
      - scene.good_morning
      - scene.dinner_time
      - scene.movie_time
      - scene.good_night


homeassistant:
  customize:
    scene.movie_time:
      icon: mdi:movie
    scene.dinner_time:
      icon: mdi:food-variant
    scene.good_morning:
      icon: mdi:brightness-5
      emulated_hue_hidden: true
    scene.good_night:
      icon: mdi:brightness-2


scene:
  - name: Movie Time
    entities:
      light.kitchen_lights_1_level:
        state: on
        brightness: 40
      light.kitchen_lights_2_level:
        state: on
        brightness: 40
      light.family_room_lights_level: off
      light.island_lights_level: off
      light.pantry_light_level: off
      switch.kitchen_cabinets_switch: off

  - name: Dinner Time
    entities:
      light.kitchen_lights_1_level:
        state: on
        brightness: 120
      light.kitchen_lights_2_level:
        state: on
        brightness: 120
      light.family_room_lights_level:
        state: on
        brightness: 40
      light.dining_room_lights_level:
        state: on
        brightness: 255
      light.island_lights_level: off
      light.pantry_light_level: off
      switch.kitchen_cabinets_switch: off

  - name: Good Morning
    entities:
      alarm_control_panel.simplisafe: "disarmed"
      switch.kitchen_cabinets_switch:
        state: on
      light.island_lights_level:
        state: on
        brightness: 127
      light.family_room_lights_level: off
      light.kitchen_lights_1_level: off
      light.kitchen_lights_2_level: off
      light.pantry_light_level: off

  - name: Good Night
    entities:
      group.Lights: off
      switch.back_yard_switch: off
      switch.house_fan_switch: off
      remote.family_room:
        state: off
      alarm_control_panel.simplisafe: "armed_home"
