group:
  security:
    name: Security
    entities:
      - binary_sensor.front_door
      - binary_sensor.family_room_doors
      - binary_sensor.dining_room_window
      - binary_sensor.living_room_window_left
      - binary_sensor.living_room_window_right
      - binary_sensor.kitchen_window
      - binary_sensor.masons_window
      - binary_sensor.brinks_window
      - binary_sensor.guest_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.master_bedroom_doors
      - binary_sensor.laundry_room_door
      - binary_sensor.jeffs_garage_door_sensor
      - binary_sensor.jillians_garage_door_sensor
      - binary_sensor.guest_garage_door_sensor


homeassistant:
  customize:
    binary_sensor.front_door:
      device_class: door
      icon: mdi:door
    binary_sensor.family_room_doors:
      device_class: door
      icon: mdi:door
    binary_sensor.dining_room_window:
      device_class: window
      icon: mdi:window-closed
    binary_sensor.living_room_window_left:
      friendly_name: Living Room Window (L)
      device_class: window
      icon: mdi:window-closed
    binary_sensor.living_room_window_right:
      friendly_name: Living Room Window (R)
      device_class: window
      icon: mdi:window-closed
    binary_sensor.kitchen_window:
      device_class: window
      icon: mdi:window-closed
    binary_sensor.masons_window:
      friendly_name: Mason's Window
      device_class: window
      icon: mdi:window-closed
    binary_sensor.brinks_window:
      friendly_name: Brink's Window
      device_class: window
      icon: mdi:window-closed
    binary_sensor.guest_window:
      device_class: window
      icon: mdi:window-closed
    binary_sensor.master_bedroom_window:
      device_class: window
      icon: mdi:window-closed
    binary_sensor.master_bedroom_doors:
      device_class: door
      icon: mdi:door
    binary_sensor.laundry_room_door:
      device_class: door
      icon: mdi:door
    binary_sensor.guest_garage_door_sensor:
      friendly_name: Guest Garage Door
      device_class: opening
      icon: mdi:garage
    binary_sensor.jeffs_garage_door_sensor:
      friendly_name: Jeff's Garage Door
      device_class: opening
      icon: mdi:garage
    binary_sensor.jillians_garage_door_sensor:
      friendly_name: Jillian's Garage Door
      device_class: opening
      icon: mdi:garage


abode:
  username: !secret abode_user
  password: !secret abode_pass
  name: Abode


skybell:
  username: !secret skybell_user
  password: !secret skybell_pass


camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_user
    password: !secret synology_pass


automation:
  - alias: Alarm - Status changes theme
    initial_state: True
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: alarm_control_panel.abode
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {% if states.alarm_control_panel.abode.state == "armed_home" %}
            alarm
          {% elif states.alarm_control_panel.abode.state == "armed_away" %}
            alarm
          {% else %}
            default
          {% endif %}

  - alias: Alarm - Say status
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.abode
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.master_bedroom
          message: >
            {% set status = states.alarm_control_panel.abode.state %}
            {% set isOpened = states.group.Security.state %}
            {%- if status == "armed_home" -%}
              Alarm armed... Home
            {%- elif status == "armed_away" -%}
              Alarm armed... Away
            {%- elif status == "disarmed" -%}
              Alarm Off
            {%- endif -%}
            {%- if isOpened == "on" and status != "disarmed" -%}
              ... Warning... The following are open:
              {%- for entity_id in states.group.Security.attributes.entity_id -%}
                {% set parts = entity_id.split('.') %}
                {%- if states(entity_id) == 'on' -%}
                  ... {{ states[parts[0]][parts[1]].name }}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}

  - alias: Alarm - Turn house off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode
      to: "armed_away"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.Lights
          - switch.back_yard_switch
          - switch.house_fan_switch
          - remote.family_room

  - alias: Alarm - Alert lighting
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: abode_alarm
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.kitchen_cabinets_switch
          - switch.living_room_switch
          - switch.entryway_light_switch
          - switch.hallway_light_switch
          - switch.back_yard_switch
          - switch.front_yard_switch
          - switch.guest_room_switch
      - service: light.turn_on
        entity_id:
          - light.kitchen_lights_1_level
          - light.kitchen_lights_2_level
          - light.island_lights_level
          - light.family_room_lights_level
          - light.pantry_light_level
          - light.dining_room_lights_level
          - light.master_bedroom_level
          - light.masons_room_level
        data:
          brightness: 255

  - alias: Alarm - Alert Pics
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: abode_alarm
    action:
      - service: script.turn_on
        entity_id: script.snapshot_cameras_and_send

  - alias: Alarm - Reminder
    initial_state: True
    trigger:
      - platform: template
        value_template: "{{ states.climate.home.attributes.away_mode == 'on' }}"
      - platform: template
        value_template: "{{ states.climate.home.attributes.hold_mode == 'away' }}"
    action:
      - condition: template
        value_template: "{{ states.alarm_control_panel.abode.state != 'armed_away' }}"
      - service: notify.jeff_and_jillians_phone
        data:
          title: Home Assistant
          message: The alarm is not armed. Are you away?

  - alias: Alarm - Fault
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: abode_panel_fault
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Home Assistant
          message: "The alarm faulted: {{ trigger.event.data }}"

  - alias: Doorbell - Notifications
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell_sensor
      to: "on"
    action:
      service: script.turn_on
      entity_id: script.snapshot_door_and_send


alert:
  garage_door_jeff:
    name: Jeff's garage is open
    entity_id: binary_sensor.jeffs_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_jillian:
    name: Jillian's garage is open
    entity_id: binary_sensor.jillians_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_guest:
    name: Guest garage is open
    entity_id: binary_sensor.guest_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone