alarm_control_panel:
  - platform: simplisafe
    username: !secret simplisafe_user
    password: !secret simplisafe_pass


abode:
  username: !secret abode_user
  password: !secret abode_pass
  name: Abode Alarm System


camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_user
    password: !secret synology_pass

automation:
  - alias: Alarm - Status changes theme
    initial_state: True
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: alarm_control_panel.simplisafe
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {% if states.alarm_control_panel.simplisafe.state == "armed_home" %}
            alarm
          {% elif states.alarm_control_panel.simplisafe.state == "armed_away" %}
            alarm
          {% else %}
            default
          {% endif %}

  - alias: Alarm - Away mode lights off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.simplisafe
      to: "armed_away"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.Lights
          - switch.back_yard_switch
          - switch.house_fan_switch
          - remote.family_room

  - alias: Alarm - Alert lighting
    initial_state: True
    trigger:
      platform: template
      value_template: "{{ states.alarm_control_panel.simplisafe.attributes.alarm != 'No Alert' }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.kitchen_cabinets_switch
          - switch.living_room_switch
          - switch.entryway_light_switch
          - switch.hallway_light_switch
          - switch.back_yard_switch
          - switch.front_yard_switch
          - switch.guest_room_switch
      - service: light.turn_on
        entity_id:
          - light.kitchen_lights_1_level
          - light.kitchen_lights_2_level
          - light.island_lights_level
          - light.family_room_lights_level
          - light.pantry_light_level
          - light.dining_room_lights_level
          - light.master_bedroom_level
          - light.masons_room_level
        data:
          brightness: 255

  - alias: Alarm - Alert Pics
    initial_state: True
    trigger:
      platform: template
      value_template: "{{ states.alarm_control_panel.simplisafe.attributes.alarm != 'No Alert' }}"
    action:
      - service: script.turn_on
        entity_id: script.snapshot_cameras_and_send

  - alias: Alarm - Reminder
    initial_state: True
    trigger:
      - platform: template
        value_template: "{{ states.climate.meadowlands.attributes.away_mode == 'on' }}"
      - platform: template
        value_template: "{{ states.climate.meadowlands.attributes.hold_mode == 'away' }}"
    action:
      - condition: template
        value_template: "{{ states.alarm_control_panel.simplisafe.state != 'armed_away' }}"
      - service: notify.jeff_and_jillians_phone
        data:
          title: Home Assistant
          message: The alarm is not armed. Are you away?

  - alias: Doorbell - Notifications
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell_sensor
      to: "on"
    action:
      service: script.turn_on
      entity_id: script.snapshot_door_and_send
