alarm_control_panel:
  - platform: simplisafe
    username: !secret simplisafe_user
    password: !secret simplisafe_pass


camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_user
    password: !secret synology_pass