group:
  Sensors:
    entities:
      - binary_sensor.jeffs_garage_door_sensor
      - binary_sensor.jillians_garage_door_sensor
      - binary_sensor.guest_garage_door_sensor

homeassistant:
  customize:
    binary_sensor.guest_garage_door_sensor:
      friendly_name: Guest Garage Door
      device_class: opening
      icon: mdi:home
    binary_sensor.jeffs_garage_door_sensor:
      friendly_name: Jeff's Garage Door
      device_class: opening
      icon: mdi:home
    binary_sensor.jillians_garage_door_sensor:
      friendly_name: Jillian's Garage Door
      device_class: opening
      icon: mdi:home


alert:
  garage_door_jeff:
    name: Jeff's garage is open
    entity_id: binary_sensor.jeffs_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_jillian:
    name: Jillian's garage is open
    entity_id: binary_sensor.jillians_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_guest:
    name: Guest garage is open
    entity_id: binary_sensor.guest_garage_door_sensor
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone


automation:
  - alias: Ringing the doorbell sends a notification
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell_sensor
      to: 'on'
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.front_door
          filename: /tmp/snapshot_doorbell.png
      - service: notify.jeff_and_jillians_phone
        data:
          title: Home Assistant
          message: Doorbell
          data:
            images:
              - /tmp/snapshot_doorbell.png