group:
  Sensors:
    control: hidden
    entities:
      - binary_sensor.jeffs_garage_door_sensor
      - binary_sensor.jillians_garage_door_sensor
      - binary_sensor.guest_garage_door_sensor
      - switch.skybell_front_door_do_not_disturb

homeassistant:
  customize:
    binary_sensor.guest_garage_door_sensor:
      friendly_name: Guest Garage Door
      device_class: opening
      icon: mdi:home
    binary_sensor.jeffs_garage_door_sensor:
      friendly_name: Jeff's Garage Door
      device_class: opening
      icon: mdi:home
    binary_sensor.jillians_garage_door_sensor:
      friendly_name: Jillian's Garage Door
      device_class: opening
      icon: mdi:home
    switch.skybell_front_door_do_not_disturb:
      friendly_name: Mute Doorbell
      icon: mdi:bell


skybell:
  username: !secret skybell_user
  password: !secret skybell_pass


switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb


alert:
  garage_door_jeff:
    name: Jeff's garage is open
    entity_id: binary_sensor.jeffs_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_jillian:
    name: Jillian's garage is open
    entity_id: binary_sensor.jillians_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone

  garage_door_guest:
    name: Guest garage is open
    entity_id: binary_sensor.guest_garage_door_sensor
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - jeff_and_jillians_phone
