group:
  Settings:
    entities:
      - input_number.delay_timer


input_number:
  delay_timer:
    name: Turn lights off
    initial: 0
    min: 0
    max: 180
    step: 5
    unit_of_measurement: Minutes