group:
  Settings:
    entities:
      - input_select.delay_timer
  Batteries:
    entities:
      - sensor.garage_jeff_battery
      - sensor.garage_jillian_battery
      - sensor.garage_guest_battery
      - sensor.doorbell_battery


homeassistant:
  customize:
    group.all_automations:
      friendly_name: Automations
      control: hidden
      hidden: false
    sensor.garage_guest_battery:
      friendly_name: Guest Garage Door
      icon: mdi:battery
    sensor.garage_jeff_battery:
      friendly_name: Jeff's Garage Door
      icon: mdi:battery
    sensor.garage_jillian_battery:
      friendly_name: Jillian's Garage Door
      icon: mdi:battery
    sensor.doorbell_battery:
      friendly_name: Doorbell
      icon: mdi:battery


input_select:
  delay_timer:
    name: Turn lights off in
    options:
      - "Select"
      - "0:15"
      - "0:30"
      - "1:00"
      - "1:30"
      - "2:00"


sensor:
  - platform: template
    sensors:
      garage_guest_battery:
        value_template: '{% if states.zwave.guest_garage_door %}
          {{ states.zwave.guest_garage_door.attributes.battery_level }}
        {% endif %}'
        unit_of_measurement: '%'

      garage_jillian_battery:
        value_template: '{% if states.zwave.jillians_garage_door %}
          {{ states.zwave.jillians_garage_door.attributes.battery_level }}
        {% endif %}'
        unit_of_measurement: '%'

      garage_jeff_battery:
        value_template: '{% if states.zwave.jeffs_garage_door %}
          {{ states.zwave.jeffs_garage_door.attributes.battery_level }}
        {% endif %}'
        unit_of_measurement: '%'

      doorbell_battery:
        value_template: '{% if states.zwave.doorbell %}
          {{ states.zwave.doorbell.attributes.battery_level }}
        {% endif %}'
        unit_of_measurement: '%'


automation:
  - alias: Delay lights off
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.delay_timer
    action:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select' }}"
      - delay: "{{ trigger.to_state.state }}"
      - service: homeassistant.turn_off
        entity_id:
          - group.Lights
      - service: input_select.select_option
        data:
          entity_id: input_select.delay_timer
          option: Select