group:
  Settings:
    control: hidden
    entities:
      - input_boolean.delayed_lights_off
      - input_boolean.disable_away_mode
      - input_boolean.disable_notify


input_boolean:
  disable_away_mode:
    name: Disable away mode
    initial: off
    icon: mdi:toggle-switch

  disable_notify:
    name: Disable notifications
    initial: off
    icon: mdi:toggle-switch

  delayed_lights_off:
    name: Lights off (delayed)
    initial: off
    icon: mdi:toggle-switch