group:
  Settings:
    entities:
      - input_select.delay_timer
      - switch.skybell_front_door_do_not_disturb


homeassistant:
  customize:
    group.all_automations:
      friendly_name: Automations
      control: hidden
      hidden: false
    switch.skybell_front_door_do_not_disturb:
      friendly_name: Mute Doorbell
      icon: mdi:bell
    input_select.delay_timer:
      icon: mdi:lightbulb


switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb


input_select:
  delay_timer:
    name: Turn lights off in
    options:
      - "Select"
      - "0:15"
      - "0:30"
      - "1:00"
      - "1:30"
      - "2:00"


automation:
  - alias: Settings - Delay lights off
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.delay_timer
    action:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select' }}"
      - delay: "{{ trigger.to_state.state }}"
      - service: homeassistant.turn_off
        entity_id:
          - group.Lights
      - service: input_select.select_option
        data:
          entity_id: input_select.delay_timer
          option: Select

  - alias: Settings - Reset at midnight
    initial_state: True
    trigger:
      platform: time
      at: "00:00:00"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.skybell_front_door_do_not_disturb
