group:
  weather:
    name: Weather
    entities:
      - sensor.outdoor_forecast
      - sensor.outdoor_temperature
      - sensor.outdoor_temperature_high


sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - temperature_high
      - hourly_summary
      - humidity

  - platform: template
    sensors:
      outdoor_temperature:
        friendly_name: Current
        value_template: "{{ states.sensor.dark_sky_temperature.state|round|int }}"
        unit_of_measurement: "°F"
        icon_template: mdi:thermometer

      outdoor_temperature_high:
        friendly_name: High
        value_template: "{{ states.sensor.dark_sky_daytime_high_temperature.state|round|int }}"
        unit_of_measurement: "°F"
        icon_template: mdi:thermometer

      outdoor_forecast:
        friendly_name: Forecast
        value_template: "{{ states.sensor.dark_sky_hourly_summary.state }}"
        icon_template: >
          {%- if "cloud" in states.sensor.dark_sky_hourly_summary.state -%}
            mdi:weather-cloudy
          {%- elif "fog" in states.sensor.dark_sky_hourly_summary.state -%}
            mdi:weather-fog
          {%- elif "rain" in states.sensor.dark_sky_hourly_summary.state -%}
            mdi:weather-rainy
          {%- elif "wind" in states.sensor.dark_sky_hourly_summary.state -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}